plugins {
    id 'com.android.library'
}

android {
    namespace 'com.aquiles.aquanotify'
    compileSdk 34
    defaultConfig {
        minSdk 24
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Clases de Godot (sacadas de godot-lib de la plantilla de exportación): solo para compilar.
    compileOnly files('libs/godot-classes.jar')
}
